### PR TITLE
updated glossary

### PR DESCRIPTION
**Pull request by HassanAkbar**
Generated glossary from [20231214 Multi-Lingual Glossary – Published __unlocked__ with Math.xlsx](https://github.com/ISO-TC211/mlgt-data/blob/main/release-6/20231214%20Multi-Lingual%20Glossary%20%E2%80%93%20Published%20__unlocked__%20with%20Math.xlsx) using `tc211-termbase`

### CODE REVIEW

**Comment by HassanAkbar** [comment]
I've updated the glossary by generating it using the updated `tc211-termbase` gem which now uses glossarist to generate concepts. 

@ReesePlews Can you help verify these changes?

Here are the other related merged PRs for the other gems that will use glossarist to read these concepts.

- The glossary is generated by `tc211-termbase` gem which was updated to use glossarist in this PR -> https://github.com/geolexica/tc211-termbase/pull/31
- Updated `jekyll-geolexica` to use the updated glossary using glossarist -> https://github.com/geolexica/jekyll-geolexica/pull/20

cc: @ronaldtse

**Comment by ReesePlews** [comment]
@HassanAkbar  thank you very much for your work on this! where can i review the changes, are they on a the public site or the staging site? please provide a URL so there is no confusion.

**Comment by ronaldtse** [comment]
Maybe we should deploy a staging site at a subsite like how it’s done in fontist/formulas ?

**Comment by ReesePlews** [comment]
@ronaldtse i agree about using the staging site. i think it would be best at this time, at least until i have the other documents ready for translation purposes. just send me the link when you are ready and i will check it. i think we have a few weeks for checking. thanks

**Comment by ReesePlews** [comment]
hello @ronaldtse can you give an update on the issue about using  stem:[...]  notation to support the math scripts? if i read correctly you and @HassanAkbar are moving forward with geolexica using the stem:[...] notation. i just wanted to confirm that.   thanks

**Comment by HassanAkbar** [comment]
@ReesePlews @ronaldtse The staging site for updated glossary with `stem:[...]` support is deployed at https://www.geolexica.org/isotc211-staging/

**Comment by ReesePlews** [comment]
@HassanAkbar thank you very much for the update. i confirm i can see the staging site. the math on a couple of items i checked looks really nice. please give me some time for checking and i will submit any issues i find to you @ronaldtse .  appreciate your diligent work on this project. thank you!

**Comment by ronaldtse** [comment]
Term 2455 (https://www.geolexica.org/isotc211-staging/concepts/2455/) contains the "latexmath:..." syntax which needs to be parsed as math in LaTeX math format by Plurimath. @HassanAkbar

**Comment by HassanAkbar** [comment]
@ronaldtse I've updated the staging site and the `latexmath:[...]` syntax is now working.

**Comment by ReesePlews** [comment]
hello @HassanAkbar i see that now in the barycentric coordinates entry. please ask @ronaldtse as he helped was working with another member on the math processing. was that the only latex instance?  that should probably be changed to stem:[ ... ] as the others.   i dont think there is a reason we would need the latex code, but please ask Ron.  thank you

**Comment by ronaldtse** [comment]
@HassanAkbar @ReesePlews so the reason why we had `latexmath:...` was because Asciimath did not have the `backepsilon` symbol. Do we now support it in Plurimath? @HassanAkbar can you please help check? Thanks!

**Comment by HassanAkbar** [comment]
@ronaldtse currently we do not support `backepsilon` in Plurimath.

**Comment by HassanAkbar** [comment]
@ronaldtse we can add support for latex symbols in Plurimath for asciimath. It shouldn't take that long for that. 
Should we add that?

**Comment by ronaldtse** [comment]
> @ronaldtse we can add support for latex symbols in Plurimath for asciimath. It shouldn't take that long for that. Should we add that?

I agree. Let's do that.

**Comment by ronaldtse** [comment]
@HassanAkbar please heal emerge this when ready, thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse This branch contains the concepts generated from the `20231214_Multi-Lingual_Glossary–Published__unlocked__withMath.xlsx` file, and we are updating this branch whenever @ReesePlews creates a new issue related to the isotc211 staging site.

Can I merge this branch or wait until all the concepts are finalized?

**Comment by ronaldtse** [comment]
Let's merge this. I don't want to wait anymore.

**Pull request merged**
