### PR TITLE
update 20231207 KR contact changes

### PR DESCRIPTION
**Pull request by ReesePlews**
update 20231207 KR contact changes

hello Hassan, could you please check the syntax of the updates and confirm the PR. thank you

@strogonoff i have asked Hassan to check this PR. there will be at least one more, either today or the next couple of days...

### CODE REVIEW

**Comment by ReesePlews** [comment]
doing some update to the received information (UTC 01:10)

**Comment by ReesePlews** [comment]
UTC 01:15 i have finished my updates. ready for check.

**Comment by ReesePlews** [comment]
hello @strogonoff and @HassanAkbar just checking the status of this update. is the "deploy issue" (https://github.com/geolexica/isotc211.geolexica.org/issues/201) still under investigation?

**Comment by ReesePlews** [comment]
hello again @strogonoff and @HassanAkbar 

i just received another change request for that register page. i will make another issue and branch later today.

i hope you can approve them together when you are ready.

thank you

**Review by HassanAkbar — APPROVED** [review]

**Pull request merged**
