### PR TITLE
Extracting domain from terms

### PR DESCRIPTION
**Pull request by HassanAkbar**
As discussed here -> https://github.com/geolexica/isotc211.geolexica.org/issues/200#issuecomment-1768258038

### CODE REVIEW

**Comment by ronaldtse** [comment]
@HassanAkbar can we merge this (or is this superseded?)

**Comment by HassanAkbar** [comment]
@ronaldtse Let me check, I'll get back to you on this.

**Comment by HassanAkbar** [comment]
@ronaldtse we still need to extract the domains from the concepts but this PR is no longer valid as this is updating old data,

What I'm thinking is to update the `tc211-termbase` gem to extract the domains when generating concepts rather than doing it afterwards on the generated concepts.
I'll open a PR in `tc211-termbase` for this change.

**Comment by ronaldtse** [comment]
@HassanAkbar is this supposed to be closed? Is the work done? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse This is not needed as this is updating old concepts, I've created a new issue for this and will open a new PR.

**Pull request closed without merging**
